"""
export_docx.py  —  Generates a structured Word document comparison report.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Optional

from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from models.schemas import ComparisonResult, SemanticChange, ImpactLevel, ChangeType


# ── Colour palette (RGB tuples) ──────────────────────────────────────────────────
RGB_AMBER     = RGBColor(0xF5, 0x9E, 0x0B)
RGB_JADE      = RGBColor(0x22, 0xC5, 0x5E)
RGB_CRIMSON   = RGBColor(0xE1, 0x1D, 0x48)
RGB_SAPPHIRE  = RGBColor(0x25, 0x63, 0xEB)
RGB_MUTED     = RGBColor(0x7A, 0x74, 0x64)
RGB_BLACK     = RGBColor(0x1A, 0x18, 0x15)
RGB_LIGHT_BG  = RGBColor(0xF5, 0xF4, 0xF0)
RGB_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)

IMPACT_RGB = {
    ImpactLevel.HIGH:   RGB_CRIMSON,
    ImpactLevel.MEDIUM: RGB_AMBER,
    ImpactLevel.LOW:    RGB_JADE,
    ImpactLevel.NONE:   RGB_MUTED,
}

CHANGE_RGB = {
    ChangeType.ADDITION:     RGB_JADE,
    ChangeType.DELETION:     RGB_CRIMSON,
    ChangeType.MODIFICATION: RGB_AMBER,
    ChangeType.REGULATORY:   RGB_SAPPHIRE,
    ChangeType.UNCHANGED:    RGB_MUTED,
}


# ── Helpers ──────────────────────────────────────────────────────────────────────

def _set_cell_bg(cell, hex_color: str):
    """Set table cell background colour."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), hex_color)
    shd.set(qn("w:val"), "clear")
    tcPr.append(shd)


def _add_horizontal_line(doc: Document):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    pPr = p._p.get_or_add_pPr()
    pb = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "D4D0C4")
    pb.append(bottom)
    pPr.append(pb)
    return p


def _para(doc: Document, text: str, bold=False, italic=False,
          size=10, color: Optional[RGBColor] = None,
          align=WD_ALIGN_PARAGRAPH.LEFT) -> None:
    p = doc.add_paragraph()
    p.alignment = align
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    if color:
        run.font.color.rgb = color


def _heading(doc: Document, text: str, level: int = 1):
    h = doc.add_heading(text, level=level)
    h.runs[0].font.color.rgb = RGB_BLACK
    return h


def _change_type_label(ct: ChangeType) -> str:
    return {
        ChangeType.ADDITION:     "Addition",
        ChangeType.DELETION:     "Deletion",
        ChangeType.MODIFICATION: "Modification",
        ChangeType.REGULATORY:   "Regulatory Update",
        ChangeType.UNCHANGED:    "Unchanged",
    }.get(ct, ct.value)


# ── Main generator ────────────────────────────────────────────────────────────────

def generate_docx(result: ComparisonResult) -> bytes:
    doc = Document()
    summary = result.summary

    # ── Page margins ─────────────────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin   = Cm(2.5)
        section.right_margin  = Cm(2.5)

    # ── Title ────────────────────────────────────────────────────────────────────
    title = doc.add_heading("Policy Comparison Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].font.color.rgb = RGB_BLACK

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Generated by PolicyLens")
    run.font.size = Pt(10)
    run.font.color.rgb = RGB_MUTED

    doc.add_paragraph()

    # ── Cover metadata table ─────────────────────────────────────────────────────
    meta_rows = [
        ("Document A (Legacy)",  result.doc1_name),
        ("Document B (Updated)", result.doc2_name),
        ("Comparison ID",        result.comparison_id[:20] + "…"),
        ("Generated",            datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")),
        ("Text Similarity",      f"{result.text_similarity_ratio * 100:.1f}%"),
        ("Overall Impact",       summary.overall_impact_level.value.upper()),
    ]
    tbl = doc.add_table(rows=len(meta_rows), cols=2)
    tbl.style = "Table Grid"
    for i, (label, value) in enumerate(meta_rows):
        tbl.cell(i, 0).text = label
        tbl.cell(i, 0).paragraphs[0].runs[0].bold = True
        tbl.cell(i, 0).paragraphs[0].runs[0].font.color.rgb = RGB_MUTED
        _set_cell_bg(tbl.cell(i, 0), "F5F4F0")
        cell_val = tbl.cell(i, 1)
        cell_val.text = value
        if label == "Overall Impact":
            cell_val.paragraphs[0].runs[0].bold = True
            cell_val.paragraphs[0].runs[0].font.color.rgb = IMPACT_RGB.get(
                summary.overall_impact_level, RGB_MUTED)

    doc.add_page_break()

    # ── Stats ────────────────────────────────────────────────────────────────────
    _heading(doc, "At a Glance", 1)
    _add_horizontal_line(doc)

    stat_labels = ["Total Changes", "Additions", "Deletions", "Modifications", "Regulatory Updates"]
    stat_values = [
        str(summary.total_changes),
        str(summary.additions),
        str(summary.deletions),
        str(summary.modifications),
        str(summary.regulatory_updates),
    ]
    stat_colors = [RGB_BLACK, RGB_JADE, RGB_CRIMSON, RGB_AMBER, RGB_SAPPHIRE]

    stat_tbl = doc.add_table(rows=2, cols=5)
    stat_tbl.style = "Table Grid"
    for j in range(5):
        val_cell = stat_tbl.cell(0, j)
        val_cell.text = stat_values[j]
        r = val_cell.paragraphs[0].runs[0]
        r.bold = True
        r.font.size = Pt(18)
        r.font.color.rgb = stat_colors[j]
        val_cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        _set_cell_bg(val_cell, "F9F8F5")

        lbl_cell = stat_tbl.cell(1, j)
        lbl_cell.text = stat_labels[j]
        lbl_cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        lbl_cell.paragraphs[0].runs[0].font.size = Pt(8)
        lbl_cell.paragraphs[0].runs[0].font.color.rgb = RGB_MUTED
        _set_cell_bg(lbl_cell, "F9F8F5")

    doc.add_paragraph()

    # ── Executive Summary ────────────────────────────────────────────────────────
    _heading(doc, "Executive Summary", 1)
    _add_horizontal_line(doc)

    for para_text in summary.executive_summary.split("\n\n"):
        if para_text.strip():
            p = doc.add_paragraph(para_text.strip())
            p.paragraph_format.space_after = Pt(6)

    if summary.key_changes:
        _heading(doc, "Key Changes", 2)
        for kc in summary.key_changes:
            doc.add_paragraph(kc, style="List Bullet")

    if summary.risk_areas:
        _heading(doc, "Risk Areas", 2)
        for ra in summary.risk_areas:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(ra)
            run.font.color.rgb = RGB_CRIMSON

    if summary.compliance_flags:
        _heading(doc, "Compliance Flags", 2)
        for cf in summary.compliance_flags:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(cf)
            run.font.color.rgb = RGB_SAPPHIRE

    doc.add_page_break()

    # ── Changes summary table ────────────────────────────────────────────────────
    _heading(doc, "Semantic Changes Overview", 1)
    _add_horizontal_line(doc)

    if not result.semantic_changes:
        doc.add_paragraph("No semantic changes were identified.")
    else:
        ch_tbl = doc.add_table(rows=1 + len(result.semantic_changes), cols=4)
        ch_tbl.style = "Table Grid"

        headers = ["Type", "Section", "Impact", "Summary"]
        for j, h in enumerate(headers):
            cell = ch_tbl.cell(0, j)
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True
            cell.paragraphs[0].runs[0].font.size = Pt(9)
            _set_cell_bg(cell, "F59E0B")

        for i, chg in enumerate(result.semantic_changes):
            bg = "F9F8F5" if i % 2 == 0 else "FFFFFF"
            ct_color = CHANGE_RGB.get(chg.change_type, RGB_MUTED)
            il_color = IMPACT_RGB.get(chg.impact_level, RGB_MUTED)

            row_cells = ch_tbl.rows[i + 1].cells

            row_cells[0].text = _change_type_label(chg.change_type)
            row_cells[0].paragraphs[0].runs[0].font.color.rgb = ct_color
            row_cells[0].paragraphs[0].runs[0].bold = True
            row_cells[0].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[1].text = chg.section or "General"
            row_cells[1].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[2].text = chg.impact_level.value.upper()
            row_cells[2].paragraphs[0].runs[0].font.color.rgb = il_color
            row_cells[2].paragraphs[0].runs[0].bold = True
            row_cells[2].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[3].text = chg.summary
            row_cells[3].paragraphs[0].runs[0].font.size = Pt(8)

            for cell in row_cells:
                _set_cell_bg(cell, bg)

    doc.add_page_break()

    # ── Detailed changes ─────────────────────────────────────────────────────────
    _heading(doc, "Detailed Change Analysis", 1)
    _add_horizontal_line(doc)

    for idx, chg in enumerate(result.semantic_changes, 1):
        _write_change_detail(doc, idx, chg)

    # ── Section alignment ────────────────────────────────────────────────────────
    if result.section_analysis and result.section_analysis.matches:
        doc.add_page_break()
        _heading(doc, "Section Alignment Analysis", 1)
        _add_horizontal_line(doc)

        sim_pct = result.section_analysis.overall_structural_similarity * 100
        p = doc.add_paragraph()
        r = p.add_run(f"Overall structural similarity: {sim_pct:.1f}%")
        r.bold = True
        r.font.size = Pt(10)

        doc.add_paragraph()

        sa_tbl = doc.add_table(
            rows=1 + len(result.section_analysis.matches[:40]), cols=4)
        sa_tbl.style = "Table Grid"
        for j, h in enumerate(["Doc A Section", "Doc B Section", "Status", "Similarity"]):
            cell = sa_tbl.cell(0, j)
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True
            cell.paragraphs[0].runs[0].font.size = Pt(9)
            _set_cell_bg(cell, "F59E0B")

        for i, m in enumerate(result.section_analysis.matches[:40]):
            bg = "F9F8F5" if i % 2 == 0 else "FFFFFF"
            row = sa_tbl.rows[i + 1].cells
            row[0].text = m.doc1_section or "—"
            row[1].text = m.doc2_section or "—"
            row[2].text = m.match_type.upper()
            row[3].text = f"{m.similarity_score:.2f}"
            for cell in row:
                _set_cell_bg(cell, bg)
                cell.paragraphs[0].runs[0].font.size = Pt(8)

    # ── Save ─────────────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def _write_change_detail(doc: Document, idx: int, chg: SemanticChange):
    ct_color = CHANGE_RGB.get(chg.change_type, RGB_MUTED)
    il_color = IMPACT_RGB.get(chg.impact_level, RGB_MUTED)

    # Header
    h = doc.add_heading(f"{idx}. {chg.summary}", 2)
    h.runs[0].font.color.rgb = RGB_BLACK

    # Badge row
    p = doc.add_paragraph()
    r1 = p.add_run(f"[{_change_type_label(chg.change_type)}]  ")
    r1.bold = True
    r1.font.color.rgb = ct_color
    r1.font.size = Pt(8)
    r2 = p.add_run(f"[{chg.impact_level.value.upper()} IMPACT]")
    r2.bold = True
    r2.font.color.rgb = il_color
    r2.font.size = Pt(8)
    if chg.section:
        r3 = p.add_run(f"  §  {chg.section}")
        r3.font.color.rgb = RGB_MUTED
        r3.font.size = Pt(8)

    # Before / After
    if chg.old_content or chg.new_content:
        ba_tbl = doc.add_table(rows=1, cols=2)
        ba_tbl.style = "Table Grid"

        def _fill_ba(cell, label: str, text: str, color: RGBColor, bg: str):
            _set_cell_bg(cell, bg)
            lp = cell.paragraphs[0]
            lr = lp.add_run(label + "\n")
            lr.bold = True
            lr.font.size = Pt(7)
            lr.font.color.rgb = color
            tr = lp.add_run(text[:300] if text else "(not present)")
            tr.font.size = Pt(8)
            tr.font.name = "Courier New"

        _fill_ba(ba_tbl.cell(0, 0), "BEFORE", chg.old_content or "", RGB_CRIMSON, "FFF1F2")
        _fill_ba(ba_tbl.cell(0, 1), "AFTER",  chg.new_content or "", RGB_JADE,    "F0FDF4")

    # Explanation
    if chg.explanation:
        p = doc.add_paragraph()
        r = p.add_run("Analysis: ")
        r.bold = True
        r.font.size = Pt(9)
        p.add_run(chg.explanation).font.size = Pt(9)

    # Impact
    for label, text, color in [
        ("Business Impact",    chg.business_impact,    RGB_AMBER),
        ("Compliance Impact",  chg.compliance_impact,  RGB_SAPPHIRE),
        ("Regulatory Impact",  chg.regulatory_impact,  RGB_JADE),
    ]:
        if text and text.strip():
            p = doc.add_paragraph()
            r = p.add_run(f"{label}: ")
            r.bold = True
            r.font.size = Pt(8)
            r.font.color.rgb = color
            p.add_run(text).font.size = Pt(8)

    # Recommendations
    if chg.recommendations:
        p = doc.add_paragraph()
        r = p.add_run("Recommended Actions:")
        r.bold = True
        r.font.size = Pt(8)
        r.font.color.rgb = RGB_AMBER
        for rec in chg.recommendations:
            doc.add_paragraph(f"→ {rec}", style="List Bullet").runs[0].font.size = Pt(8)

    doc.add_paragraph()
