"""
export_docx.py  —  Generates a structured Word document comparison report.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Optional, Sequence

from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from models.schemas import ComparisonResult, SemanticChange, ImpactLevel, ChangeType


# ── Colour palette (RGB tuples) ──────────────────────────────────────────────────
RGB_AMBER     = RGBColor(0xF5, 0x9E, 0x0B)
RGB_JADE      = RGBColor(0x22, 0xC5, 0x5E)
RGB_CRIMSON   = RGBColor(0xE1, 0x1D, 0x48)
RGB_SAPPHIRE  = RGBColor(0x25, 0x63, 0xEB)
RGB_MUTED     = RGBColor(0x7A, 0x74, 0x64)
RGB_BLACK     = RGBColor(0x1A, 0x18, 0x15)
RGB_LIGHT_BG  = RGBColor(0xF5, 0xF4, 0xF0)
RGB_WHITE     = RGBColor(0xFF, 0xFF, 0xFF)

IMPACT_RGB = {
    ImpactLevel.HIGH:   RGB_CRIMSON,
    ImpactLevel.MEDIUM: RGB_AMBER,
    ImpactLevel.LOW:    RGB_JADE,
    ImpactLevel.NONE:   RGB_MUTED,
}

CHANGE_RGB = {
    ChangeType.ADDITION:     RGB_JADE,
    ChangeType.DELETION:     RGB_CRIMSON,
    ChangeType.MODIFICATION: RGB_AMBER,
    ChangeType.REGULATORY:   RGB_SAPPHIRE,
    ChangeType.UNCHANGED:    RGB_MUTED,
}


# ── Helpers ──────────────────────────────────────────────────────────────────────

def _set_cell_bg(cell, hex_color: str):
    """Set table cell background colour."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), hex_color)
    shd.set(qn("w:val"), "clear")
    tcPr.append(shd)


def _allow_row_split(tbl):
    """Allow table rows to break across pages (prevents blank pages)."""
    for row in tbl.rows:
        tr = row._tr
        trPr = tr.get_or_add_trPr()
        for cs in trPr.findall(qn("w:cantSplit")):
            trPr.remove(cs)


def _add_horizontal_line(doc: Document):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    pPr = p._p.get_or_add_pPr()
    pb = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "D4D0C4")
    pb.append(bottom)
    pPr.append(pb)
    return p


def _para(doc: Document, text: str, bold=False, italic=False,
          size=10, color: Optional[RGBColor] = None,
          align=WD_ALIGN_PARAGRAPH.LEFT) -> None:
    p = doc.add_paragraph()
    p.alignment = align
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    if color:
        run.font.color.rgb = color


def _heading(doc: Document, text: str, level: int = 1):
    h = doc.add_heading(text, level=level)
    h.runs[0].font.color.rgb = RGB_BLACK
    # Prevent default Word heading style from injecting a page break
    # on top of our explicit doc.add_page_break() calls.
    h.paragraph_format.page_break_before = False
    return h


def _change_type_label(ct: ChangeType) -> str:
    return {
        ChangeType.ADDITION:     "Addition",
        ChangeType.DELETION:     "Deletion",
        ChangeType.MODIFICATION: "Modification",
        ChangeType.REGULATORY:   "Regulatory Update",
        ChangeType.UNCHANGED:    "Unchanged",
    }.get(ct, ct.value)


# ── Main generator ────────────────────────────────────────────────────────────────

def generate_docx(result: ComparisonResult, annotations: Optional[Sequence[Any]] = None) -> bytes:
    doc = Document()
    summary = result.summary
    annotation_map = _group_annotations(annotations or [])

    # ── Page margins ─────────────────────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin   = Cm(2.5)
        section.right_margin  = Cm(2.5)

    # ── Title ────────────────────────────────────────────────────────────────────
    title = doc.add_heading("Policy Comparison Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].font.color.rgb = RGB_BLACK

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.paragraph_format.space_after = Pt(12)
    run = subtitle.add_run("Generated by PolicyLens")
    run.font.size = Pt(10)
    run.font.color.rgb = RGB_MUTED

    # ── Cover metadata table ─────────────────────────────────────────────────────
    meta_rows = [
        ("Document A (Legacy)",  result.doc1_name),
        ("Document B (Updated)", result.doc2_name),
        ("Comparison ID",        result.comparison_id[:20] + "…"),
        ("Generated",            datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")),
        ("Text Similarity",      f"{result.text_similarity_ratio * 100:.1f}%"),
        ("Overall Impact",       summary.overall_impact_level.value.upper()),
    ]
    tbl = doc.add_table(rows=len(meta_rows), cols=2)
    tbl.style = "Table Grid"
    for i, (label, value) in enumerate(meta_rows):
        tbl.cell(i, 0).text = label
        tbl.cell(i, 0).paragraphs[0].runs[0].bold = True
        tbl.cell(i, 0).paragraphs[0].runs[0].font.color.rgb = RGB_MUTED
        _set_cell_bg(tbl.cell(i, 0), "F5F4F0")
        cell_val = tbl.cell(i, 1)
        cell_val.text = value
        if label == "Overall Impact":
            cell_val.paragraphs[0].runs[0].bold = True
            cell_val.paragraphs[0].runs[0].font.color.rgb = IMPACT_RGB.get(
                summary.overall_impact_level, RGB_MUTED)

    doc.add_page_break()

    # ── Stats ────────────────────────────────────────────────────────────────────
    _heading(doc, "At a Glance", 1)
    _add_horizontal_line(doc)

    stat_labels = ["Total Changes", "Additions", "Deletions", "Modifications", "Regulatory Updates"]
    stat_values = [
        str(summary.total_changes),
        str(summary.additions),
        str(summary.deletions),
        str(summary.modifications),
        str(summary.regulatory_updates),
    ]
    stat_colors = [RGB_BLACK, RGB_JADE, RGB_CRIMSON, RGB_AMBER, RGB_SAPPHIRE]

    stat_tbl = doc.add_table(rows=2, cols=5)
    stat_tbl.style = "Table Grid"
    for j in range(5):
        val_cell = stat_tbl.cell(0, j)
        val_cell.text = stat_values[j]
        r = val_cell.paragraphs[0].runs[0]
        r.bold = True
        r.font.size = Pt(18)
        r.font.color.rgb = stat_colors[j]
        val_cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        _set_cell_bg(val_cell, "F9F8F5")

        lbl_cell = stat_tbl.cell(1, j)
        lbl_cell.text = stat_labels[j]
        lbl_cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        lbl_cell.paragraphs[0].runs[0].font.size = Pt(8)
        lbl_cell.paragraphs[0].runs[0].font.color.rgb = RGB_MUTED
        _set_cell_bg(lbl_cell, "F9F8F5")

    # ── Document statistics rendered on the frontend ────────────────────────────
    _heading(doc, "Document Statistics", 2)
    doc_stats_tbl = doc.add_table(rows=1, cols=5)
    doc_stats_tbl.style = "Table Grid"
    for j, h in enumerate(["Document", "Pages", "Words", "Characters", "Sections"]):
        cell = doc_stats_tbl.cell(0, j)
        cell.text = h
        cell.paragraphs[0].runs[0].bold = True
        _set_cell_bg(cell, "F59E0B")

    for label, stats in [
        ("Document A (Legacy)", result.doc1_stats),
        ("Document B (Updated)", result.doc2_stats),
    ]:
        row = doc_stats_tbl.add_row().cells
        row[0].text = label
        row[1].text = str(stats.total_pages)
        row[2].text = f"{stats.total_words:,}"
        row[3].text = f"{stats.total_characters:,}"
        row[4].text = str(len(stats.sections_detected))
        for cell in row:
            cell.paragraphs[0].runs[0].font.size = Pt(8)

    for label, sections in [
        ("Document A Detected Sections", result.doc1_sections),
        ("Document B Detected Sections", result.doc2_sections),
    ]:
        if sections:
            _heading(doc, label, 3)
            for section_name in sections:
                doc.add_paragraph(section_name, style="List Bullet")

    # ── Executive Summary ────────────────────────────────────────────────────────
    _heading(doc, "Executive Summary", 1)
    _add_horizontal_line(doc)

    for para_text in summary.executive_summary.split("\n\n"):
        if para_text.strip():
            p = doc.add_paragraph(para_text.strip())
            p.paragraph_format.space_after = Pt(6)

    if summary.key_changes:
        _heading(doc, "Key Changes", 2)
        for kc in summary.key_changes:
            doc.add_paragraph(kc, style="List Bullet")

    if summary.risk_areas:
        _heading(doc, "Risk Areas", 2)
        for ra in summary.risk_areas:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(ra)
            run.font.color.rgb = RGB_CRIMSON

    if summary.compliance_flags:
        _heading(doc, "Compliance Flags", 2)
        for cf in summary.compliance_flags:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(cf)
            run.font.color.rgb = RGB_SAPPHIRE

    doc.add_page_break()

    # ── Changes summary table ────────────────────────────────────────────────────
    _heading(doc, "Semantic Changes Overview", 1)
    _add_horizontal_line(doc)

    if not result.semantic_changes:
        doc.add_paragraph("No semantic changes were identified.")
    else:
        ch_tbl = doc.add_table(rows=1 + len(result.semantic_changes), cols=4)
        ch_tbl.style = "Table Grid"

        headers = ["Type", "Section", "Impact", "Summary"]
        for j, h in enumerate(headers):
            cell = ch_tbl.cell(0, j)
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True
            cell.paragraphs[0].runs[0].font.size = Pt(9)
            _set_cell_bg(cell, "F59E0B")

        for i, chg in enumerate(result.semantic_changes):
            bg = "F9F8F5" if i % 2 == 0 else "FFFFFF"
            ct_color = CHANGE_RGB.get(chg.change_type, RGB_MUTED)
            il_color = IMPACT_RGB.get(chg.impact_level, RGB_MUTED)

            row_cells = ch_tbl.rows[i + 1].cells

            row_cells[0].text = _change_type_label(chg.change_type)
            row_cells[0].paragraphs[0].runs[0].font.color.rgb = ct_color
            row_cells[0].paragraphs[0].runs[0].bold = True
            row_cells[0].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[1].text = chg.section or "General"
            row_cells[1].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[2].text = chg.impact_level.value.upper()
            row_cells[2].paragraphs[0].runs[0].font.color.rgb = il_color
            row_cells[2].paragraphs[0].runs[0].bold = True
            row_cells[2].paragraphs[0].runs[0].font.size = Pt(8)

            row_cells[3].text = chg.summary
            row_cells[3].paragraphs[0].runs[0].font.size = Pt(8)

            for cell in row_cells:
                _set_cell_bg(cell, bg)

    doc.add_page_break()

    # ── Detailed changes ─────────────────────────────────────────────────────────
    _heading(doc, "Detailed Change Analysis", 1)
    _add_horizontal_line(doc)

    for idx, chg in enumerate(result.semantic_changes, 1):
        _write_change_detail(doc, idx, chg, annotation_map.get(chg.id, []))

    # ── Section alignment ────────────────────────────────────────────────────────
    if result.section_analysis and result.section_analysis.matches:
        doc.add_page_break()
        _heading(doc, "Section Alignment Analysis", 1)
        _add_horizontal_line(doc)

        sim_pct = result.section_analysis.overall_structural_similarity * 100
        p = doc.add_paragraph()
        r = p.add_run(f"Overall structural similarity: {sim_pct:.1f}%")
        r.bold = True
        r.font.size = Pt(10)
        p.paragraph_format.space_after = Pt(8)

        counts = {
            "unchanged": sum(1 for m in result.section_analysis.matches if m.match_type == "unchanged"),
            "modified": sum(1 for m in result.section_analysis.matches if m.match_type == "modified"),
            "added": sum(1 for m in result.section_analysis.matches if m.match_type == "added"),
            "deleted": sum(1 for m in result.section_analysis.matches if m.match_type == "deleted"),
        }
        _para(
            doc,
            "Section counts: "
            f"unchanged={counts['unchanged']}, modified={counts['modified']}, "
            f"added={counts['added']}, deleted={counts['deleted']}",
            size=9,
            color=RGB_MUTED,
        )

        if result.section_analysis.semantic_clone_pairs:
            _heading(doc, "Semantic Clone Sections", 2)
            for h1, h2 in result.section_analysis.semantic_clone_pairs:
                doc.add_paragraph(f"{h1} ↔ {h2}", style="List Bullet")

        sa_tbl = doc.add_table(
            rows=1 + len(result.section_analysis.matches), cols=4)
        sa_tbl.style = "Table Grid"
        for j, h in enumerate(["Doc A Section", "Doc B Section", "Status", "Similarity"]):
            cell = sa_tbl.cell(0, j)
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True
            cell.paragraphs[0].runs[0].font.size = Pt(9)
            _set_cell_bg(cell, "F59E0B")

        for i, m in enumerate(result.section_analysis.matches):
            bg = "F9F8F5" if i % 2 == 0 else "FFFFFF"
            row = sa_tbl.rows[i + 1].cells
            row[0].text = m.doc1_section or "—"
            row[1].text = m.doc2_section or "—"
            row[2].text = m.match_type.upper()
            row[3].text = f"{m.similarity_score:.2f}"
            for cell in row:
                _set_cell_bg(cell, bg)
                cell.paragraphs[0].runs[0].font.size = Pt(8)

        _heading(doc, "Section Match Details", 2)
        for idx, m in enumerate(result.section_analysis.matches, 1):
            _heading(doc, f"{idx}. {m.match_type.title()} - {m.doc1_section or 'Not present'} / {m.doc2_section or 'Not present'}", 3)
            _para(doc, f"Similarity score: {m.similarity_score:.4f}", bold=True, size=8)
            side_tbl = doc.add_table(rows=1, cols=2)
            side_tbl.style = "Table Grid"
            _allow_row_split(side_tbl)
            _fill_docx_text_cell(side_tbl.cell(0, 0), f"Document A - {m.doc1_section or 'Not present'}", m.doc1_content or "Section not present in Document A", "FFF1F2")
            _fill_docx_text_cell(side_tbl.cell(0, 1), f"Document B - {m.doc2_section or 'Not present'}", m.doc2_content or "Section not present in Document B", "F0FDF4")

        if result.section_analysis.similarity_matrix:
            _heading(doc, "Section Cosine Similarity Matrix", 2)
            _para(
                doc,
                f"Rows = Document A ({len(result.section_analysis.doc1_section_labels)} sections); "
                f"columns = Document B ({len(result.section_analysis.doc2_section_labels)} sections).",
                size=8,
                color=RGB_MUTED,
            )
            for i, row in enumerate(result.section_analysis.similarity_matrix):
                label = result.section_analysis.doc1_section_labels[i] if i < len(result.section_analysis.doc1_section_labels) else f"Row {i + 1}"
                values = " | ".join(f"{v:.3f}" for v in row)
                _add_mono_block(doc, f"{label}: {values}")

    # ── Text diff data ──────────────────────────────────────────────────────────
    doc.add_page_break()
    _heading(doc, "Text Diff - Changed Blocks", 1)
    _add_horizontal_line(doc)
    changed_chunks = [c for c in result.diff_chunks if c.type != ChangeType.UNCHANGED]
    if not changed_chunks:
        doc.add_paragraph("No textual differences detected.")
    for idx, chunk in enumerate(changed_chunks, 1):
        _heading(doc, f"{idx}. {_change_type_label(chunk.type)} - {chunk.section or 'General'}", 2)
        diff_tbl = doc.add_table(rows=1, cols=2)
        diff_tbl.style = "Table Grid"
        _allow_row_split(diff_tbl)
        _fill_docx_text_cell(diff_tbl.cell(0, 0), "Document A", chunk.old_text or "—", "FFF1F2")
        _fill_docx_text_cell(diff_tbl.cell(0, 1), "Document B", chunk.new_text or "—", "F0FDF4")

    # ── Full source text as shown in side-by-side frontend view ─────────────────
    doc.add_page_break()
    _heading(doc, "Full Source Text - Document A", 1)
    _add_horizontal_line(doc)
    _add_mono_block(doc, result.doc1_content)

    doc.add_page_break()
    _heading(doc, "Full Source Text - Document B", 1)
    _add_horizontal_line(doc)
    _add_mono_block(doc, result.doc2_content)

    # ── Save ─────────────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def _write_change_detail(doc: Document, idx: int, chg: SemanticChange, annotations: Sequence[Any]):
    ct_color = CHANGE_RGB.get(chg.change_type, RGB_MUTED)
    il_color = IMPACT_RGB.get(chg.impact_level, RGB_MUTED)

    # Header
    h = doc.add_heading(f"{idx}. {chg.summary}", 2)
    h.runs[0].font.color.rgb = RGB_BLACK

    # Badge row
    p = doc.add_paragraph()
    r1 = p.add_run(f"[{_change_type_label(chg.change_type)}]  ")
    r1.bold = True
    r1.font.color.rgb = ct_color
    r1.font.size = Pt(8)
    r2 = p.add_run(f"[{chg.impact_level.value.upper()} IMPACT]")
    r2.bold = True
    r2.font.color.rgb = il_color
    r2.font.size = Pt(8)
    if chg.section:
        r3 = p.add_run(f"  §  {chg.section}")
        r3.font.color.rgb = RGB_MUTED
        r3.font.size = Pt(8)

    # Before / After
    if chg.old_content or chg.new_content:
        ba_tbl = doc.add_table(rows=1, cols=2)
        ba_tbl.style = "Table Grid"
        _allow_row_split(ba_tbl)

        def _fill_ba(cell, label: str, text: str, color: RGBColor, bg: str):
            _set_cell_bg(cell, bg)
            lp = cell.paragraphs[0]
            lr = lp.add_run(label)
            lr.bold = True
            lr.font.size = Pt(7)
            lr.font.color.rgb = color
            lp.add_run("\n").font.size = Pt(7)

            text = text or ""
            if not text:
                lp.add_run("(not present)").font.size = Pt(8)
                return

            paragraphs = text.split("\n\n")
            for i, para in enumerate(paragraphs):
                if i > 0:
                    lp = cell.add_paragraph()
                if len(para) > 2000:
                    for start in range(0, len(para), 2000):
                        chunk = para[start:start + 2000]
                        if start > 0:
                            lp = cell.add_paragraph()
                        run = lp.add_run(chunk)
                        run.font.size = Pt(8)
                        run.font.name = "Courier New"
                else:
                    run = lp.add_run(para)
                    run.font.size = Pt(8)
                    run.font.name = "Courier New"

        _fill_ba(ba_tbl.cell(0, 0), "BEFORE", chg.old_content or "", RGB_CRIMSON, "FFF1F2")
        _fill_ba(ba_tbl.cell(0, 1), "AFTER",  chg.new_content or "", RGB_JADE,    "F0FDF4")

    # Explanation
    if chg.explanation:
        p = doc.add_paragraph()
        r = p.add_run("Analysis: ")
        r.bold = True
        r.font.size = Pt(9)
        p.add_run(chg.explanation).font.size = Pt(9)

    # Impact
    for label, text, color in [
        ("Business Impact",    chg.business_impact,    RGB_AMBER),
        ("Compliance Impact",  chg.compliance_impact,  RGB_SAPPHIRE),
        ("Regulatory Impact",  chg.regulatory_impact,  RGB_JADE),
    ]:
        if text and text.strip():
            p = doc.add_paragraph()
            r = p.add_run(f"{label}: ")
            r.bold = True
            r.font.size = Pt(8)
            r.font.color.rgb = color
            p.add_run(text).font.size = Pt(8)

    # Recommendations
    if chg.recommendations:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(4)
        r = p.add_run("Recommended Actions:")
        r.bold = True
        r.font.size = Pt(8)
        r.font.color.rgb = RGB_AMBER
        for rec in chg.recommendations:
            doc.add_paragraph(f"→ {rec}", style="List Bullet").runs[0].font.size = Pt(8)

    if annotations:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(6)
        r = p.add_run("Comments:")
        r.bold = True
        r.font.size = Pt(8)
        r.font.color.rgb = RGB_AMBER
        for ann in annotations:
            status = "resolved" if bool(_ann_get(ann, "resolved")) else "open"
            created = _ann_get(ann, "created_at")
            author = _ann_get(ann, "author") or "Reviewer"
            text = _ann_get(ann, "text") or ""
            doc.add_paragraph(
                f"[{status}] {author} ({created}): {text}",
                style="List Bullet",
            ).runs[0].font.size = Pt(8)


def _fill_docx_text_cell(cell, label: str, text: str, bg: str):
    _set_cell_bg(cell, bg)
    p = cell.paragraphs[0]
    r = p.add_run(label)
    r.bold = True
    r.font.size = Pt(7)
    p.add_run("\n").font.size = Pt(7)

    text = text or ""
    if not text:
        p.add_run("(not present)").font.size = Pt(8)
        return

    # Split into paragraphs so the cell can flow across pages
    paragraphs = text.split("\n\n")
    for i, para in enumerate(paragraphs):
        if i > 0:
            p = cell.add_paragraph()
        if len(para) > 2000:
            for start in range(0, len(para), 2000):
                chunk = para[start:start + 2000]
                if start > 0:
                    p = cell.add_paragraph()
                run = p.add_run(chunk)
                run.font.size = Pt(8)
                run.font.name = "Courier New"
        else:
            run = p.add_run(para)
            run.font.size = Pt(8)
            run.font.name = "Courier New"


def _add_mono_block(doc: Document, text: str, chunk_size: int = 3500):
    text = text or ""
    if not text:
        doc.add_paragraph("(empty)")
        return
    for start in range(0, len(text), chunk_size):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(3)
        run = p.add_run(text[start:start + chunk_size])
        run.font.size = Pt(8)
        run.font.name = "Courier New"


def _ann_get(annotation: Any, key: str):
    if isinstance(annotation, dict):
        return annotation.get(key)
    return getattr(annotation, key, None)


def _group_annotations(annotations: Sequence[Any]) -> dict[str, list[Any]]:
    grouped: dict[str, list[Any]] = {}
    for ann in annotations:
        change_id = _ann_get(ann, "change_id")
        if not change_id:
            continue
        grouped.setdefault(change_id, []).append(ann)
    return grouped